### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by ayazvayani** [radean/dmvdm#5]
New Address:
House No. B-81, Block-9, Gulshan-e-Iqbal, near Aziz Bhatii Park, Karachi

Remove PTCL No.
LOGO Bottom 2018-2019.

**Comment by radean** [comment]
Done

**Comment by ayazvayani** [comment]
Hyperlink: mouserhover text color change. it is merging with ground.

**Comment by radean** [comment]
Done

**Comment by ayazvayani** [comment]
remove terms: not yet decided

**Comment by radean** [comment]
done
